server:
  port: 8081

spring:
  application:
    name: auth-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/dhftgo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
