server:
  port: 8081

spring:
  application:
    name: auth-service

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/dhftgo_authdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Logging config
logging:
  level:
    org.springframework.security: DEBUG
